# Generated by Django 4.2.1 on 2023-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.TextField(max_length=255, verbose_name='장소'),
        ),
    ]
