# Generated by Django 4.2.1 on 2023-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.TextField(blank=True, verbose_name='장소'),
        ),
    ]
