# Generated by Django 4.2.1 on 2023-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
